apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-game-secret
  labels:
    app: 2048-game
    release: {{ .Release.Name }}
type: Opaque
stringData:
  API_PORT: {{ .Values.game.api.port | toString | quote }}
  DB_HOST: "mysql"
  DB_PORT: {{ .Values.mysql.service.port | toString | quote }}
  DB_USER: {{ .Values.mysql.auth.username | quote }}
  DB_PASSWORD: {{ .Values.mysql.auth.password | quote }}
  DB_NAME: {{ .Values.mysql.auth.database | quote }}
