apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-2048-game
  labels:
    app: 2048-game
    release: {{ .Release.Name }}
spec:
  rules:
    - host: 2048-game.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-2048-game
                port:
                  number: {{ .Values.service.port }}
