apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-2048-game
  labels:
    app: 2048-game
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.game.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app: 2048-game
    release: {{ .Release.Name }}
